### ISSUE TITLE
error r: 132

### ISSUE THREAD

**Issue by jesnstevens** [slu-soc5050/Week-05#1]
Hi @chris-prener, 

Hope things are going well. I'm getting near to completing Problem Set 03 but I'm encountering an error when I run my master do-file. At the end after exporting my graphs and the analysis do file runs the quietly log close mardoc command stata comes up with "too few quotes r(132);" 

I've attached a screenshot for clarification. I didn't edit those commands prior to it running the error the first time, I tried editing the quotations and command to troubleshoot and I haven't been able too. The only thing I can think of is that I updated Stata yesterday, and this is the first time its trying to replace the markdoc file, but I'm not sure why that would come up with "too few quotes r(132)." error.  

![screen shot 2016-09-21 at 7 21 40 pm](https://cloud.githubusercontent.com/assets/21069023/18733808/d210446a-8033-11e6-875a-f1a56cbb1c0c.png)

If you have any suggestions, or troubleshooting techniques I could try I'd greatly appreciate it! 

Thanks,
@jesnstevens

**Comment by jesnstevens** [comment]
@chris-prener, 

Well I thought I added a screenshot but I can't see it from my end. If you can't either let me know and I can email it to you, and email my log/do-file. Whatever might help clarify. 

Thanks,
@jesnstevens

**Comment by chris-prener** [comment]
Hi @jesnstevens ,
Thanks for reaching out - check out [the Week 03 Jotter](https://github.com/slu-soc5050/Core-Documents/wiki/Week-03) and see if that explanation helps you get through this pesky error!

@chris-prener
